name: "Jekyll sample tutorial"
description: "Jekyll sample tutorial"

url: "http://hanumanthraju.github.io/jekyll-tutorial/"

host:        0.0.0.0
port:        4001
baseurl:     /jekyll-tutorial
markdown: rdiscount
permalink: pretty
pygments: true
